### ISSUE TITLE
update app to Rails 5.2 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#685]

**Comment by tyranja** [comment]
http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html

**Comment by tyranja** [comment]
We can use active storage once we upgraded: http://edgeguides.rubyonrails.org/5_2_release_notes.html#active-storage instead of the gem carrierwave https://github.com/carrierwaveuploader/carrierwave

**Comment by tyranja** [comment]
Erro when testing in  production: 

```
2018-06-03T19:18:36.710130+00:00 heroku[router]: at=info method=GET path="/en/" host=speakerinnen.org request_id=b0ae9ff3-cc5c-46f5-bc67-978aad6d1896 fwd="78.55.233.201" dyno=web.1 connect=1ms service=300ms status=500 bytes=871 protocol=https
2018-06-03T19:18:36.688727+00:00 app[web.1]: #<ActiveRecord::Relation [#<Category id: 8, created_at: "2014-04-02 20:03:06", updated_at: "2014-04-02 20:03:06", name: nil>, #<Category id: 2, created_at: "2014-04-02 19:59:25", updated_at: "2014-05-12 19:20:43", name: "Diversity">, #<Category id: 3, created_at: "2014-04-02 20:00:10", updated_at: "2014-05-12 19:20:50", name: "Internet & Media">, #<Category id: 4, created_at: "2014-04-02 20:00:31", updated_at: "2014-05-12 19:20:59", name: "Body & Soul">, #<Category id: 7, created_at: "2014-04-02 20:02:45", updated_at: "2014-05-12 19:21:11", name: "Arts & Culture">, #<Category id: 9, created_at: "2014-04-02 20:03:18", updated_at: "2014-05-12 19:21:30", name: "Politics & Society">, #<Category id: 10, created_at: "2014-04-02 20:03:43", updated_at: "2014-05-12 19:21:48", name: "Companies & Start-ups">, #<Category id: 11, created_at: "2014-04-02 20:03:57", updated_at: "2014-05-12 19:21:56", name: "Science & Technology">, #<Category id: 1, created_at: "2014-04-02 19:59:07", updated_at: "2015-12-11 18:47:35", name: "Career & Education">]>
2018-06-03T19:18:36.693322+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896]   Category Load (3.7ms)  SELECT "categories"."id", "categories"."created_at", "categories"."updated_at" FROM "categories" WHERE (id <> '12')
2018-06-03T19:18:36.695674+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896]   CACHE Category::Translation Load (0.0ms)  SELECT "category_translations".* FROM "category_translations" WHERE "category_translations"."category_id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9)  [["category_id", 8], ["category_id", 2], ["category_id", 3], ["category_id", 4], ["category_id", 7], ["category_id", 9], ["category_id", 10], ["category_id", 11], ["category_id", 1]]
2018-06-03T19:18:36.707001+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896] Completed 500 Internal Server Error in 287ms (ActiveRecord: 61.7ms)
2018-06-03T19:18:36.708485+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896]
2018-06-03T19:18:36.708535+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896] ArgumentError (comparison of NilClass with String failed):
2018-06-03T19:18:36.708585+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896]
2018-06-03T19:18:36.708640+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896] app/models/category.rb:12:in `sort_by'
2018-06-03T19:18:36.708643+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896] app/models/category.rb:12:in `sorted_categories'
2018-06-03T19:18:36.708645+00:00 app[web.1]: [b0ae9ff3-cc5c-46f5-bc67-978aad6d1896] app/controllers/pages_controller.rb:4:in `home'
```

**Comment by tyranja** [comment]
The solution was that `Marketing&PR` category had no english translation and therefore in the english version no `name` attribute. Changed it on staging and master.

**Comment by tyranja** [comment]
That is done.
